{% set name = "py-multihash" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0ade4de820afdc4b4aaa40464ec86c9da5cae3a4578cda2daab4b0eb7e5b18d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - base58 >=1.0.2,<3.0
    - morphys >=1.0,<2.0
    - python
    - six >=1.10.0,<2.0
    - varint >=1.0.2,<2.0

test:
  imports:
    - multihash
  requires:
    - pytest
    - pytest-cov

about:
  home: https://github.com/multiformats/multihash
  summary: Multihash implementation in Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/multiformats/py-multihash

extra:
  recipe-maintainers:
    - Aloisius
