{% set name = "py-multibase" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d28a20efcbb61eec28f55827a0bf329c7cea80fffd933aecaea6ae8431267fe4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - morphys >=1.0,<2.0
    - python
    - python-baseconv >=1.2.0,<2.0
    - six >=1.10.0,<2.0

test:
  imports:
    - multibase
  requires:
    - pytest
    - pytest-runner

about:
  home: https://github.com/multiformats/py-multibase
  summary: Multibase implementation for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Aloisius
