{% set name = "morphys" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mkalinski/morphys/archive/0642a71126c32cd26b3a443a5cac27e4e1f7240f.zip
  sha256: 3786fc3ba5542d26ca1b1af495047594ef29e9ba8208dbb748f53e725247328e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - morphys

about:
  home: https://github.com/mkalinski/morphys
  summary: Smart conversions between unicode and bytes types for common cases
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aloisius
