{% set name = "python-baseconv" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0539f8bd0464013b05ad62e0a1673f0ac9086c76b43ebf9f833053527cd9931b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: https://github.com/semente/python-baseconv
  summary: Convert numbers from base 10 integers to base X strings and back again.
  license: BSD-4-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Aloisius