{% set name = "py-cid" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22f432cc6fb68d12a9c35dbdc92c95484fc49e31dfcb9e0efb0082233c5394e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - base58 >=1.0.2,<2.0
    - morphys >=1.0,<2.0
    - py-multibase >=1.0.0,<2.0.0
    - py-multicodec <0.3.0
    - py-multihash >=0.2.0,<1.0.0
    - python

test:
  imports:
    - cid
  commands:
    - pip check
  requires:
    - pytest
    - pytest-cov
    - pip

about:
  home: https://github.com/ipld/py-cid
  summary: Self-describing content-addressed identifiers for distributed systems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Aloisius
